# Generated by Django 3.1.6 on 2021-05-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awads', '0007_auto_20210529_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='AssetName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reason',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='urgent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
