# Generated by Django 3.1.6 on 2021-05-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awads', '0009_auto_20210530_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=200, null=True),
        ),
    ]
